#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/content ]; then
    mkdir $OPENSHIFT_DATA_DIR/content
fi

if [ ! -d $OPENSHIFT_DATA_DIR/content/uploads ]; then
    mkdir $OPENSHIFT_DATA_DIR/content/uploads
fi

if [ ! -d $OPENSHIFT_DATA_DIR/content/plugins ]; then
    mkdir $OPENSHIFT_DATA_DIR/content/plugins
fi

if [ ! -d $OPENSHIFT_DATA_DIR/content/themes ]; then
    mkdir $OPENSHIFT_DATA_DIR/content/themes
fi

# Add multisite upload dir
if [ ! -d $OPENSHIFT_DATA_DIR/blogs.dir ]; then
    mkdir $OPENSHIFT_DATA_DIR/blogs.dir
fi

echo "<?php ?>" > $OPENSHIFT_DATA_DIR/content/plugins
echo "<?php ?>" > $OPENSHIFT_DATA_DIR/content/themes

ln -s $OPENSHIFT_DATA_DIR/content $OPENSHIFT_REPO_DIR/php/wp/wp-content
